name: gallery

services:
  nginx-api:
    image: alonecat/24contenthost-gallery-api-nginx
    restart: unless-stopped
    volumes:
      - app_data:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - app
    networks:
      - content_host_network

  app:
    image: alonecat/24contenthost-gallery-api
    environment:
      - APP_KEY=$APP_KEY
      - APP_NAME=$APP_NAME
      - APP_ENV=$APP_ENV
      - APP_URL=$APP_URL
      - FRONTEND_URL=$FRONTEND_URL
      - SESSION_DOMAIN=$SESSION_DOMAIN
      - SANCTUM_STATEFUL_DOMAINS=$SANCTUM_STATEFUL_DOMAINS
      - DB_CONNECTION=$DB_CONNECTION
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - APP_DEBUG=$APP_DEBUG
    volumes:
      - app_data:/var/www
    depends_on:
      - db
    networks:
      - content_host_network

  migrate:
    image: alonecat/24contenthost-gallery-api
    command: >
      sh -c "
        echo 'Waiting for DB to be ready...'
        sleep 10 && 
        php artisan migrate --force"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
    depends_on:
      - db
    networks:
      - content_host_network
    deploy:
      replicas: 0

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - content_host_network

  app-client:
    image: alonecat/24contenthost-gallery-client:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      VITE_BASE_URL: ${VITE_BASE_URL}
    networks:
      - content_host_network

networks:
  content_host_network:
    external: true

volumes:
  app_data:
  mysql_data:
