name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      g
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no {{ secrets.SSH_USER }}@{{ secrets.SSH_HOST }} << 'EOF'
            cd ~/gallery-api-deploy
            docker-compose pull  
            docker-compose up -d 
          EOF
